backend:
  name: github
  repo: MrDeldar/blog
  branch: main
  auth_scope: repo
  auth_endpoint: oauth
  client_id: "0v231iceL6BAgxrJB60S"
  client_secret: "5f5f676f7fd8f29baf48d30cbc6690f90336e1ef"

media_folder: "images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "مطالب وبلاگ"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "عنوان مطلب", name: "title", widget: "string"}
      - {label: "متن مطلب", name: "body", widget: "markdown"}
